# Generated by Django 4.0.4 on 2022-04-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_onibus'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='onibus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.onibus'),
        ),
    ]
